Vagrant.configure("2") do |config|

  config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box"
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "web" do |web|
  end

  config.vm.define "db" do |db|
  end
end