Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--groups", "/hotshell-vagrant-example"]
  end

  config.vm.define "web"
  config.vm.define "db"
end